from typing import List


def get_odd_collatz(n: int) -> List[int]:
    '''
    Return a sorted list of distinct odd numbers that appear in the Collatz sequence
    starting from n and including 1. The Collatz sequence is generated by:
        n -> n/2 if n is even
        n -> 3*n + 1 if n is odd
    Raises:
        ValueError: if n is not a positive integer.
    '''
    if not isinstance(n, int) or n <= 0:
        raise ValueError('n must be a positive integer')

    odd_values = set()
    while True:
        if n % 2 == 1:
            odd_values.add(n)
        if n == 1:
            break
        if n % 2 == 0:
            n //= 2
        else:
            n = 3 * n + 1

    return sorted(odd_values)
